### ISSUE TITLE
add feature to run it on a production environment

### ISSUE THREAD

**Issue by onlinebizsoft** [Smile-SA/magento2-module-debug-toolbar#12]
1. We could add a setting (or use an existing one from Magento) where we can restrict the IP address to show the toolbar (must work with Varnish/FPC)
2. Another option is adding a parameter on URL to activate the toolbar.

**Comment by guvra** [comment]
Hi @onlinebizsoft , after some testing, it doesn't seem to be possible to implement an IP access list, because guest visitors don't have a X-Magento-Vary cookie when they access the website for the 1st time.

For example, let's say the homepage is not cached yet.
Someone authorized to see the profiler browses the homepage.
Varnish will cache this page.

Then another visitor access the homepage.
Since he doesn't have a X-Vary cookie, he will get the page that is already in the cache. So he will see the profiler, even if his IP is not in the access list.

**Comment by onlinebizsoft** [comment]
@guvra Yes I think the option 1 can't work itself without any other steps. But we can combine (or just do) the option 2.

In order to activate the toolbar, they could add a parameter to the URL, the parameter to prevent the page cached in varnish, also we validate the IP to attempt showing the toolbar or not.
And even, we can setup a special Vary when the toolbar is activated with parameter so any sub-sequence request will have the toolbar activated without parameter needed?

**Comment by erfanimani** [comment]
I'm not sure how useful this is for everyone, considering production environments usually have New Relic, Datadog, Scout, Blackfire or other APM tools installed. This module is very useful during development.
